# FROM node:16.15.1
FROM node:18.17.0


WORKDIR /app

# for caching optimisations
COPY package*.json ./
RUN npm install
# required to serve the react app on the live server
# RUN npm install -g serve

# COPY . /app
COPY src ./src
COPY public ./public
COPY next-env.d.ts .
COPY next.config.mjs .
COPY postcss.config.mjs .
COPY tailwind.config.ts .
COPY tsconfig.json .


# # noop files for non python projects and local development
# RUN echo "#!/bin/bash" > /app/migrate.sh && chmod +x /app/migrate.sh
# RUN echo "#!/bin/bash" > /usr/local/bin/start && chmod +x /usr/local/bin/start

# ENV PATH=/node_modules/.bin:$PATH
# ENV PORT=80
# ENV HOST=0.0.0.0
# ENV BROWSER='none'

# RUN npm run build

# EXPOSE 3000

CMD ["npm", "run", "dev"]
