services:
  web:
    build: ./backend/.
    ports:
      - "8000:5000"
    environment: {}
    volumes:
      - ./backend:/backend
    # depends_on:
    #   - "redis"

  # redis:
  #   # image: "redis:alpine"
  #   image: "redis/redis-stack:latest"
  #   ports:
  #     -"6379:6379"
  #     -"8001:8001"
  frontend:
    build:
      context: ./frontend/.
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
    # restart: always

    # command: npm run dev

    # command: npm dev

    #   - "80:80"
    # command: npm start
# services:
#   # The web container is an instance of exactly the same Docker image as your
#   # Cloud application container.
#   web:
#     build: .
#     # Change the port if you'd like to expose your project locally on a
#     # different port, for example if you already use port 8000 for
#     # something else.
#     ports:
#       - "8000:80"
#     volumes:
#       - ".:/app:rw"
#     # There is currently a bug: https://github.com/facebook/create-react-app/issues/8688#issuecomment-602149917
#     tty: true
#     # The default command that the container starts with. If you'd like to run
#     # the project locally in Live configuration, you will need to change this.
#     # See https://docs.divio.com/en/latest/how-to/local-in-live-mode
#     command: npm start
